version: '3.5'

x-common-variables: &common-variables
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_DB: "play"
  POSTGRES_URL: "jdbc:postgresql://postgres:5432/play"

services:
  postgres:
    image: "postgres:alpine"
    container_name: "postgres"
    ports:
      - "5432:5432"
    environment: *common-variables
    restart: always
  alignment-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - "80:9000"
    environment: *common-variables
    restart: always
  pgadmin:
    image: "dpage/pgadmin4"
    container_name: "pgadmin"
    depends_on:
      - postgres
    ports:
      - "9090:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL
      - PGADMIN_DEFAULT_PASSWORD
